development:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["API_KEY"] %>
  api_secret: <%= ENV["SECRET_API_KEY"] %>

production:
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  api_key: <%= ENV["API_KEY"] %>
  api_secret: <%= ENV["SECRET_API_KEY"] %>
